name: Build and deploy ASP.Net Core app to Azure Web App - disaster-api-tanaboon

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      # Restore solution
      - name: Restore
        run: dotnet restore DisasterApi.sln

      # Build solution
      - name: Build
        run: dotnet build DisasterApi.sln --configuration Release --no-restore

      # Run tests
      - name: Run tests
        run: dotnet test DisasterApi.sln --no-build --no-restore --configuration Release

      # Publish ONLY API project
      - name: Publish API
        run: dotnet publish DisasterApi/DisasterApi.csproj -c Release -o ./publish

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: api-package
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: api-package

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_322BE78CAE914F1C9511E97540B0DBE1 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_22BC5672846345E583E18C2CB146041A }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_42D908B97DA1473C9B3A3C9ABD8FF4FD }}

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: disaster-api-tanaboon
          package: .
